name: "My Custom JavaScript Action"
description: "A simple GitHub Action that prints a greeting message"
author: "raghu1211"
inputs:
  name:
    description: "The name of the person to greet"
    required: true
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
runs:
  using: "node16"
  main: "index.js"

